#!/bin/bash


CURRENT_VOLUME=$(amixer sget Master | grep 'Left:' | awk -F'[][]' '{print $2}')
CURRENT_STATE=$(amixer sget Master | grep 'Left:' | awk -F'[][]' '{print $4}')
if [ "$CURRENT_STATE" == "off" ]
then
		COLOR="#D8512E"
		ICON='<span size="large">🕪</span>'
else
		COLOR="#c6c6c6"
		ICON='<span size="large" color="grey">🕪</span>'

fi
echo "<span color=\"$COLOR\">$ICON $CURRENT_VOLUME</span>"
